export const USER_INVOICES_HEAD = [
  { value: "Client ID", key: "clientId" },
  { value: "Client name", key: "clientName" },
  { value: "Phone number", key: "phoneNumber" },
  { value: "Address Type", key: "addressType" },
  { value: "Delivery date", key: "deliveryDate" },
  { value: "Date of order placed", key: "createdAt" },
  { value: "Invoice number", key: "invoiceNumber" },
  { value: "Net value €", key: "netVal" },
  { value: "Amount of VAT €", key: "vatVal" },
  { value: "Total value €", key: "totalPayments" },
  { value: "Payment status", key: "paymentStatus" },
];

export const InvoicesTableHeadCells = [
  {
    id: "clientId",
    numeric: false,
    disablePadding: true,
    sortable: true,
    label: "tableHeadCells.clientId",
    columns: "Client ID",
  },
  {
    id: "clientName",
    numeric: false,
    disablePadding: true,
    label: "tableHeadCells.name",
    sortable: false,
    columns: "Client name",
  },
  {
    id: "phoneNumber",
    numeric: false,
    disablePadding: true,
    label: "tableHeadCells.contact",
    sortable: false,
    columns: "Phone Number",
  },
  {
    id: "addressType",
    numeric: false,
    disablePadding: true,
    sortable: false,
    label: "tableHeadCells.addressType",
    columns: "Address Type",
  },
  {
    id: "deliveryDate",
    numeric: true,
    disablePadding: false,
    label: "tableHeadCells.date",
    sortable: true,
    columns: "Delivery Date",
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "tableHeadCells.created",
    sortable: true,
    columns: "Date of order placed",
  },
  {
    id: "invoiceNumber",
    numeric: false,
    disablePadding: false,
    label: "tableHeadCells.invoiceNumber",
    sortable: true,
  },
  {
    id: "netVal",
    numeric: true,
    disablePadding: false,
    label: "tableHeadCells.netVal",
    sortable: false,
  },
  {
    id: "vatVal",
    numeric: true,
    disablePadding: false,
    label: "tableHeadCells.vatVal",
    sortable: false,
  },
  {
    id: "totalPayments",
    numeric: true,
    disablePadding: false,
    label: "tableHeadCells.total",
    sortable: false,
  },

  {
    id: "paymentStatus",
    numeric: false,
    disablePadding: false,
    label: "tableHeadCells.payStatus",
    sortable: true,
    columns: "Payment Status",
  },
  {
    id: "invoice",
    numeric: false,
    disablePadding: false,
    label: "",
    sortable: false,
    columns: "invoice",
  },
];
